server:
  port: 8080
  error:
    include-message: always

app:
  seed:
    users: true
    buddies: false
  profile-image:
    storage-path: ${APP_PROFILE_IMAGE_STORAGE_PATH:${user.dir}/uploads/profile}
    url-prefix: /uploads/profile

spring:
  application:
    name: haru-api

  datasource:
    url: jdbc:mysql://localhost:3306/haru
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  logging:
    level:
      org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
